matrix:
  include:
    - language: node_js
      node_js: "8"
      script:
        - yarn build
        - yarn lint
        - yarn test-travis

    - language: python
      python: 2.7
      before_script:
        - pip install -r python/requirements.txt
      script:
        - python/run-python-tests.py

    - language: python
      python: 3.6
      before_script:
        - pip install -r python/requirements.txt
      script:
        - python/run-python-tests.py
